/**
 * Response types for offline fetch handling.
 * Defines the structure of responses generated by the offline system.
 */

import type { InertiaPage, RouteMeta, SystemKey } from './db.js';

/** Type for a cached response from the database */
export interface CachedResponse extends Response {
	/** Indicates this is a cached response */
	fromCache: boolean;
	/** The timestamp when this was cached (if applicable) */
	cachedAt?: number;
}

/** Type for offline navigation responses */
export interface OfflineNavigationResponse {
	/** The response body (HTML or JSON) */
	body: string | Blob;
	/** HTTP status code (typically 200 or 503) */
	status: number;
	/** HTTP headers */
	headers: Record<string, string>;
	/** Response content type */
	contentType: 'text/html' | 'application/json';
}

/** Export commonly-used types */
export type { InertiaPage, RouteMeta, SystemKey };
